version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 381922912532.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t job-sourcing-lambda-parsing-test-env-repo .
      - docker tag job-sourcing-lambda-parsing-test-env-repo:latest 381922912532.dkr.ecr.eu-west-1.amazonaws.com/job-sourcing-lambda-parsing-test-env-repo:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 381922912532.dkr.ecr.eu-west-1.amazonaws.com/job-sourcing-lambda-parsing-test-env-repo:latest
